version: '3.4'

services:
  account.api:
    image: ${DOCKER_REGISTRY-}account
    build:
      context: ../
      dockerfile: src/Services/Account/Account.API/Dockerfile

  note.api:
    image: ${DOCKER_REGISTRY-}note
    build:
      context: ../
      dockerfile: src/Services/Note/Note.API/Dockerfile

