apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-api
  labels:
    app: note-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: note-api
    spec:
      containers:
        - name: note-api
          image: mcmillward/takenote-note:latest
          ports:
            - containerPort: 80
