apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-db
  labels:
    app: note-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: note-db
    spec:
      containers:
        - name: note-db
          image: mcr.microsoft.com/mssql/server:2017-latest
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: note-db-cred
                  key: NOTEDB_PASSWORD
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sqldata
      volumes:
        - name: sqldata
          emptyDir: {}
