apiVersion: batch/v1
kind: Job
metadata:
  name: note-db-liquibase-GIT_VERSION_HERE
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 100
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: liquibase
          image: mcmillward/takenote-note-db-update:latest
          command: ["/bin/bash", "./entrypoint.sh"]
          env:
            - name: NOTEDB_JDBC_URL
              value: jdbc:sqlserver://note-db-svc:1433
            - name: NOTEDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: note-db-cred
                  key: NOTEDB_USERNAME
            - name: NOTEDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: note-db-cred
                  key: NOTEDB_PASSWORD
      restartPolicy: Never
