name: build and deploy
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: build note
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: src/Services/Note/Note.API
          repository: mcmillward/takenote-note
          tags: latest
