name: Build and Deploy
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build and Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build and Push Note
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: src/Services/Note/Note.API/Dockerfile
          repository: mcmillward/takenote-note
          tags: latest
      - name: Deploy Note API to Cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: '"rollout restart deployment.apps/note-api"'
      - name: Build and Push Note DB Liquibase
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: src/Database/Note/LiquibaseDockerfile
          repository: mcmillward/takenote-note-db-update
          tags: latest
      - name: Set Version for Note DB Liquibase Job
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "[GIT_VERSION_HERE]"
          replace: ${{ github.sha }}
      - name: Run Note DB Liquibase Job
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: '"apply -f deploy/kubernetes/note-db-liquibase.yaml"'
